<a href="https://colab.research.google.com/github/AthiraPG-3/MachineLearning-DeepLearning-Models/blob/main/linearRegressionUmemployment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/umemployment.csv',encoding='utf-8')
print(df.shape)
df.describe()

(574, 5)

                pce            pop     psavert     uempmed      unemploy
count    574.000000     574.000000  574.000000  574.000000    574.000000
mean    4843.510453  257189.381533    7.936585    8.610105   7771.557491
std     3579.287206   36730.801593    3.124394    4.108112   2641.960571
min      507.400000  198712.000000    1.900000    4.000000   2685.000000
25%     1582.225000  224896.000000    5.500000    6.000000   6284.000000
50%     3953.550000  253060.000000    7.700000    7.500000   7494.000000
75%     7667.325000  290290.750000   10.500000    9.100000   8691.000000
max    12161.500000  320887.000000   17.000000   25.200000  15352.000000

In [ ]:
import os
print(os.listdir("/content/drive/MyDrive/Colab Notebooks"))

['umemployment.csv', 'regressionexample (1).csv', 'housing.csv.zip', 'Untitled0.ipynb', 'linearRegressionUmemployment.ipynb']

In [ ]:
target_column = ['unemploy']
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df.describe()

              pce         pop     psavert     uempmed      unemploy
count  574.000000  574.000000  574.000000  574.000000    574.000000
mean     0.398266    0.801495    0.466858    0.341671   7771.557491
std      0.294313    0.114466    0.183788    0.163020   2641.960571
min      0.041722    0.619258    0.111765    0.158730   2685.000000
25%      0.130101    0.700857    0.323529    0.238095   6284.000000
50%      0.325087    0.788627    0.452941    0.297619   7494.000000
75%      0.630459    0.904651    0.617647    0.361111   8691.000000
max      1.000000    1.000000    1.000000    1.000000  15352.000000

In [ ]:
X = df[predictors].values
y = df[target_column].values
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(401, 4)
(173, 4)

In [ ]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [ ]:
c = lr.intercept_
m = lr.coef_
print(m,c)

[[ 57136.93088835   3844.74800161 -20217.45840519  14163.09952897]] [-36618.6927015]

In [ ]:
pred_train_lr= lr.predict(X_train)
print(np.sqrt(mean_squared_error(y_train,pred_train_lr)))
pred_test_lr= lr.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,pred_test_lr)))

971.0295047627517
1019.3232585671176

In [ ]:
X_new = np.array([[603.5, 202677, 11.7, 4.4]])
Y_new = lr.predict(X_new)
print(Y_new)

[[1.15682112e+10]]